# Generated by Django 2.2.6 on 2019-11-02 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20191026_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
